# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  me: '%env(resolve:ME_ID)%'
  host: '%env(resolve:HOST)%'
  application_file:
    url: '%env(resolve:APPLICATION_FILE_URL)%'
    text: '%env(resolve:APPLICATION_FILE_TEXT)%'
  locale: fr